---
include:
  - board: bridges_v2_left
    artifact-name: bridges_v2_54_left
    cmake-args: -DDTS_EXTRA_CPPFLAGS="-DBRIDGES_LEFT"
  - board: bridges_v2_right
    artifact-name: bridges_v2_54_right
    cmake-args: -DDTS_EXTRA_CPPFLAGS="-DBRIDGES_RIGHT_CONFIG"
